server:
  port: 11030

spring:
  application:
    name: infra-zipkin-stream-server-es
  sleuth:
    enabled: false # current application don't use sleuth
  host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

zipkin:
  storage:
    StorageComponent: elasticsearch
    type: elasticsearch
  elasticsearch:
    cluster: elasticsearch-zipkin-cluster
    host: 127.0.0.1:9300
    max-requests: 64
    index: zipkin
    index-shards: 5
    index-replicas: 1
