server:
  port: 11030

spring:
  application:
    name: infra-zipkin-stream-server-es
  sleuth:
    enabled: false # current application don't use sleuth
  host: "${cloud.docker.host}"
    port: 5672
    username: stayrascal
    password: stayrascal

zipkin:
  storage:
    StorageComponent: elasticsearch
    type: elasticsearch
  elasticsearch:
    cluster: elasticsearch-zipkin-cluster
    host: "${cloud.docker.host}:9300"
    max-requests: 64
    index: zipkin
    index-shards: 5
    index-replicas: 1

---
spring:
  profiles:
    active: docker
cloud:
  docker:
    host: 192.168.99.100
