server:
  port: 9411

spring:
  application:
    name: infra-zipkin-stream-server-es
  sleuth:
    enabled: false # current application don't use sleuth
    sampler:
      percentage: 1.0
  rabbitmq:
    host: ${cloud.docker.host}
    port: 5672
    username: stayrascal
    password: stayrascal
    virtual-host: /

zipkin:
  storage:
    type: elasticsearch
    StorageComponent: elasticsearch
    elasticsearch:
      cluster: docker-cluster
      max-requests: 64
      index: zipkin
      index-shards: 5
      index-replicas: 1
      hosts: ${cloud.docker.host}:9200

---
spring:
  profiles:
    active: docker
cloud:
  docker:
    host: 192.168.99.100

---
spring:
  profiles: default
cloud:
  docker:
    host: localhost