mysql:
  image: mysql:5.6
  ports:
    - '3306:3306'
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: service
  command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']