version: "2"
services:
  infra-eureka-server:
    image: stayrascal/infra-eureka-server
    container_name: infra-eureka-server
    ports:
      - '8761:8761'

  infra-config-server:
    image: stayrascal/infra-config-server
    container_name: infra-config-server
    ports:
      - '8888:8888'
    command: ["/apps/docker/wait-for-it.sh", "-s", "-t", "60", "infra-eureka-server:8761", "--", "./run.sh"]
    depends_on:
      - infra-eureka-server

  infra-api-gateway:
    image: stayrascal/infra-api-gateway
    container_name: infra-api-gateway
    ports:
      - '8765:8765'
    command: ["/apps/docker/wait-for-it.sh", "-s", "-t", "60", "infra-config-server:8888", "--", "./run.sh"]
    depends_on:
      - infra-config-server

  bff-staff:
    image: stayrascal/bff-staff
    container_name: bff-staff
    ports:
      - '8082:8082'
    command: ["/apps/docker/wait-for-it.sh", "-s", "-t", "60", "infra-config-server:8888", "--", "./run.sh"]
    depends_on:
      - infra-config-server

  service-user:
    image: stayrascal/service-user
    container_name: service-user
    ports:
      - '8078:8078'
    command: ["/apps/docker/wait-for-it.sh", "-s", "-t", "60", "infra-config-server:8888", "--", "./run.sh"]
    depends_on:
      - infra-config-server
#
#  service-order:
#    image: stayrascal/service-order
#    container_name: service-order
#    ports:
#      - '8079:8079'
#    command: ["/apps/docker/wait-for-it.sh", "-s", "-t", "60", "infra-config-server:8888", "--", "./run.sh"]
#    depends_on:
#      - infra-config-server

  service-address:
    image: stayrascal/service-address
    container_name: service-address
    ports:
      - '8085:8085'
    command: ["/apps/docker/wait-for-it.sh", "-s", "-t", "60", "infra-config-server:8888", "--", "./run.sh"]
    depends_on:
      - infra-config-server

  service-organization:
    image: stayrascal/service-organization
    container_name: service-organization
    ports:
      - '8086:8086'
    command: ["/apps/docker/wait-for-it.sh", "-s", "-t", "60", "infra-config-server:8888", "--", "./run.sh"]
    depends_on:
      - infra-config-server

#  service-product:
#    image: stayrascal/service-product
#    container_name: service-product
#    ports:
#      - '8087:8087'
#    command: ["/apps/docker/wait-for-it.sh", "-s", "-t", "60", "infra-config-server:8888", "--", "./run.sh"]
#    depends_on:
#      - infra-config-server

  service-mapping:
    image: stayrascal/service-mapping
    container_name: service-mapping
    ports:
      - '8089:8089'
    command: ["/apps/docker/wait-for-it.sh", "-s", "-t", "60", "infra-config-server:8888", "--", "./run.sh"]
    depends_on:
      - infra-config-server

#  infra-zipkin-server:
#    image: stayrascal/infra-zipkin-server
#    container_name: infra-zipkin-server
#    ports:
#      - '9411:9411'
#    command: ["/apps/docker/wait-for-it.sh", "-s", "-t", "60", "infra-config-server:8888", "--", "./run.sh"]
#    depends_on:
#      - infra-config-server

  infra-zipkin-stream-server:
    image: stayrascal/infra-zipkin-stream-server
    container_name: infra-zipkin-stream-server
    ports:
      - '9411:9411'
    command: ["/apps/docker/wait-for-it.sh", "-s", "-t", "60", "infra-config-server:8888", "--", "./run.sh"]
    depends_on:
      - infra-config-server

#  infra-zipkin-stream-server-es:
#    image: stayrascal/infra-zipkin-stream-server-es
#    container_name: infra-zipkin-stream-server-es
#    ports:
#      - '9411:9411'
#    command: ["/apps/docker/wait-for-it.sh", "-s", "-t", "60", "infra-config-server:8888", "--", "./run.sh"]
#    depends_on:
#      - infra-config-server

#  infra-config-client:
#    image: stayrascal/infra-config-client
#    container_name: infra-config-client
#    ports:
#      - '7888:7888'
#    command: ["/apps/docker/wait-for-it.sh", "-s", "-t", "60", "infra-config-server:8888", "--", "./run.sh"]
#    depends_on:
#      - infra-config-server
#
