version: "2"
services:
  infra-eureka-server:
    image: stayrascal/infra-eureka-server
    ports:
      - '8761:8761'

  infra-eureka-server:
      image: stayrascal/infra-zipkin
      ports:
        - '9411:9411'

  infra-config-server:
    image: stayrascal/infra-config-server
    ports:
      - '8888:8888'
    command: ["/apps/docker/wait-for-it.sh", "-s", "-t", "20", "infra-eureka-server:8761", "--", "./run.sh"]
    depends_on:
      - infra-eureka-server