eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://192.168.99.100:8761/eureka/

server:
  port: 8765

  zuul:
    routes:
      bff-staff:
        path: /desktop/staff/**
        serviceId: service-staff-desktop-bff