spring:
  application:
    name: infra-zipkin-stream-server
  datasource:
    username: stayrascal
    password: stayrascal
    url: jdbc:mysql://192.168.99.100:3306/infra-zipkin?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    schema: classpath:/zipkin-mysql.sql
    initialize: true
    continue-on-error: true
    driver-class-name: com.mysql.jdbc.Driver
  sleuth:
    enabled: false
    sampler:
      percentage: 1.0
  rabbitmq:
    host: ${cloud.docker.host}
    port: 5672
    username: stayrascal
    password: stayrascal
    virtual-host: /

server:
  port: 9412

zipkin:
  storage:
    type: mysql


---
spring:
  profiles:
    active: docker
cloud:
  docker:
    host: 192.168.99.100

---
spring:
  profiles: default
cloud:
  docker:
    host: localhost

