version: '2'

services:
  infra-zipkin-db:
    image: mysql:5.7
    container_name: infra-zipkin-db
    restart: always
    user: "1000:50"
    environment:
      - MYSQL_ROOT_PASSWORD=stayrascal
      - MYSQL_DATABASE=infra-zipkin
      - MYSQL_USER=stayrascal
      - MYSQL_PASSWORD=stayrascal
    ports:
      - "3306:3306"
    volumes:
      - ~/workspace/data/zipkin:/var/lib/mysql

  service-user-db:
    image: mysql:5.7
    container_name: service-user-db
    restart: always
    user: "1000:50"
    environment:
      - MYSQL_ROOT_PASSWORD=stayrascal
      - MYSQL_DATABASE=service-user
      - MYSQL_USER=stayrascal
      - MYSQL_PASSWORD=stayrascal
    ports:
      - "13306:3306"
    volumes:
      - ~/workspace/data/service/user:/var/lib/mysql

  service-order-db:
    image: mysql:5.7
    container_name: service-order-db
    restart: always
    user: "1000:50"
    environment:
      - MYSQL_ROOT_PASSWORD=stayrascal
      - MYSQL_DATABASE=service-order
      - MYSQL_USER=stayrascal
      - MYSQL_PASSWORD=stayrascal
    ports:
      - "23306:3306"
    volumes:
      - ~/workspace/data/service/order:/var/lib/mysql

  service-store-db:
    image: mysql:5.7
    container_name: service-store-db
    restart: always
    user: "1000:50"
    environment:
      - MYSQL_ROOT_PASSWORD=stayrascal
      - MYSQL_DATABASE=service-store
      - MYSQL_USER=stayrascal
      - MYSQL_PASSWORD=stayrascal
    ports:
      - "33306:3306"
    volumes:
      - ~/workspace/data/service/store:/var/lib/mysql

  service-address-db:
    image: mysql:5.7
    container_name: service-address-db
    restart: always
    user: "1000:50"
    environment:
      - MYSQL_ROOT_PASSWORD=stayrascal
      - MYSQL_DATABASE=service-address
      - MYSQL_USER=stayrascal
      - MYSQL_PASSWORD=stayrascal
    ports:
      - "43306:3306"
    volumes:
      - ~/workspace/data/service/address:/var/lib/mysql

  service-organization-db:
    image: mysql:5.7
    container_name: service-organization-db
    restart: always
    user: "1000:50"
    environment:
      - MYSQL_ROOT_PASSWORD=stayrascal
      - MYSQL_DATABASE=service-organization
      - MYSQL_USER=stayrascal
      - MYSQL_PASSWORD=stayrascal
    ports:
      - "53306:3306"
    volumes:
      - ~/workspace/data/service/organization:/var/lib/mysql

  service-product-db:
    image: mysql:5.7
    container_name: service-product-db
    restart: always
    user: "1000:50"
    environment:
      - MYSQL_ROOT_PASSWORD=stayrascal
      - MYSQL_DATABASE=service-product
      - MYSQL_USER=stayrascal
      - MYSQL_PASSWORD=stayrascal
    ports:
      - "63306:3306"
    volumes:
      - ~/workspace/data/service/product:/var/lib/mysql