spring:
  application:
    name: infra-config-client
  sleuth:
    sampler:
      percentage: 1.0
    web:
      skip-pattern: (^cleanup.*|.+favicon.*)
  rabbitmq:
      port: 5672
      host: "${cloud.docker.host}"
      username: stayrascal
      password: stayrascal
#  logging:
#    level:
#      org.springframework.web: DEBUG
#      org.hibernate: DEBUG
#    file: logs/application.log
#    pattern: "%d %-5level %logger : %msg%n"
#    file: "%d %-5level [%thread] %logger : %msg%n"

server:
  port: 7888

management:
  context-path: /
  security:
      enabled: false

---
spring:
  profiles: default
cloud:
  docker:
    host: localhost

---
spring:
  profiles: docker
cloud:
  docker:
    host: 192.168.99.100
