spring:
  application:
    name: infra-config-client
  sleuth:
    sampler:
      percentage: 1.0
    web:
      skip-pattern: (^cleanup.*|.+favicon.*)
  rabbitmq:
      port: 5672
      host: ${cloud.docker.host}
      username: stayrascal
      password: stayrascal

server:
  port: 7888

management:
  context-path: /
  security:
      enabled: false

elasticsearch:
  clustername: rascal-cluster
  host: localhost
  port: 9300

---
spring:
  profiles: default
cloud:
  docker:
    host: localhost

---
spring:
  profiles: docker
cloud:
  docker:
    host: 192.168.99.100
