spring:
  application:
    name: infra-config-client
  sleuth:
    sampler:
      percentage: 1.0
    web:
      skip-pattern: (^cleanup.*|.+favicon.*)
#  rabbitmq:
#      port: 5672
#      host: localhost
#      username: springcloud
#      password: 123456
#  logging:
#    level:
#      org.springframework.web: DEBUG
#      org.hibernate: DEBUG
#    file: logs/application.log
#    pattern: "%d %-5level %logger : %msg%n"
#    file: "%d %-5level [%thread] %logger : %msg%n"


server:
  port: 7888

management:
  context-path: /
  security:
      enabled: false
