spring:
  application:
    name: infra-api-gateway
  sleuth:
    sampler:
      percentage: 1.0
    web:
      skip-pattern: (^cleanup.*|.+favicon.*)
  rabbitmq:
    port: 5672
    host: "${cloud.docker.host}"
    username: stayrascal
    password: stayrascal
  redis:
    database: 0
    timeout: 10
    host: localhost
    port: 6379
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0

server:
  port: 8765
  tomcat:
    accesslog:
      enabled: true
      directory: /apps/boot/logs


logging:
  level:
    com.stayrascal.cloud: info
  config: classpath:logback-spring.xml

zuul:
  ratelimit:
    enabled: true #default false
    behind-proxy: true #default false
    policies:
      bff-staff:
        limit: 10
        refresh-interval: 120 #60 default value (in seconds)
        type: #optional
          - user
          - origin
          - url
  host:
    max-per-route-connections: 500
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000


ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OKToRetryOnAllOperations: false
  eureka:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000