spring:
  application:
    name: service-staff-desktop-bff
  jersey:
    application-path: /desktop/staff
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    base-url: http://localhost:9411

cloud:
  jersey:
    access_control_allow_origin: '*'

  auth:
    admin_token_expire_minutes: 30
    allow_public_access: true

server:
  servlet-path: /
  context-path: /
  port: 8082

management:
  context-path: /system

eureka:
  instance:
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  server:
    enable-self-preservation: false

logging:
  level:
    org.springframework.web: debug

---
spring:
  profiles: local
  zipkin:
    enabled: false
    base-url: http://localhost:9411