spring:
  application:
    name: service-staff-desktop-bff
  jersey:
    application-path: /desktop/staff
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    base-url: http://zipkin-service:9411

server:
  port: 8080
  context-path: /
  servlet-path: /

management:
  context-path: /system

eureka:
  instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  server:
    enableSelfPreservation: false

logging:
  level:
    org.springframework.web: DEBUG

---
spring:
  profiles: local
  zipkin:
    enabled: false
    base-url: http://localhost:9411