spring:
  application:
    name: service-staff-desktop-bff
  jersey:
    application-path: /desktop/staff
  sleuth:
    sampler:
      percentage: 1
  rabbitmq:
    port: 5672
    host: ${cloud.docker.host}
    username: stayrascal
    password: stayrascal

cloud:
  auth:
    admin_token_expire_minutes: 30
    allow_public_access: true
  jersey:
    access_control_allow_origin: '*'
    swagger:
      version: '0.0.1'
      host: 'localhost:8080'
      scheme: 'http'
      base-path: '/desktop/staff'
#  redis:
#    host: localhost
#  jms:
#    url: tcp://localhost:61616
#    username: korprulu
#    password: korprulu

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 5000
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 1000
        sleepWindowInMilliseconds: 5000
        errorThresholdPercentage: 50

server:
  servlet-path: /
  context-path: /
  port: 8082
  tomcat:
    accesslog:
      enabled: true
      directory: /apps/boot/logs

management:
  context-path: /system

eureka:
  instance:
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  server:
    enable-self-preservation: false

logging:
  level:
    org.springframework.web: info
    com.stayrascal.cloud: info
  config: classpath:logback-spring.xml