info:
  profile: default
  descript: '{cipher}AEBbR/EjScTmAYVGjU2P9cU42ezkn794fDnVeM3b+eaPtLZBAJLOgxi0gXOksoCGwUeGDCKU58spaby0fhTWXUZYuuIP0LujMC8EseISlaI5jTKpHvm/5Rm+ZexUGkeSSVOmA7cxhxv58rJJIuFwcM4s'
cloud:
  docker:
    host: localhost

