spring:
  application:
    name: infra-spring-boot-admin
  boot:
    admin:
      url: : http://localhost:11007
      username: "${security.user.name}"
      password: "${security.user.password}"
      client:
        metadata:
          user.name: "${security.user.name}"
          user.password: "${security.user.password}"
      hazelcast:
        enabled: true
        application-store: msa-admin-applicaiton-store
        event-store: msa=admin-admin-event-store


server:
  port: 11007
  tomcat:
    accesslog:
      enabled: true
      directory: /apps/boot/logs

logging:
  level:
    com.stayrascal.cloud: info
  config: classpath:logback-spring.xml

security:
  user:
    name: admin
    password: admin

management:
  context-path: "/actuator"
  security:
    enabled: false