spring:
  application:
    name: service-user
  aop:
    auto: true
    proxy-target-class: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jersey:
    application-path: /rest
  sleuth:
    sampler:
      percentage: 1

flyway:
  enabled: true
  out-of-order: true
  encoding: UTF-8

cloud:
  jersey:
    access_control_allow_origin: '*'
  auth:
    admin_token_expire_minutes: 30
    allow_public_access: true
  allowReloadTestData: true
  auth:
    randomKeyLength: 6
    email:
      defaultKeyExpireMinutes: 1440
      title:
      contentTemplate:

  redis:
    host: localhost

  jms:
    url: tcp://localhost:61616
    username: cloud
    password: cloud


hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 1000
      circuitBreaker:
        enabled: true
        requestvolumeThreshold: 1000
        sleepWindowInMilliseconds: 5000
        errorThresholdPercentage: 50


server:
  port: 8078
  context-path: /
  servlet-path: /

management:
  context-path: /system

eureka:
  instance:
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR

endpoints:
  env:
    enabled: true