spring:
  application:
    name: service-user
  aop:
    auto: true
    proxy-target-class: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jersey:
    application-path: /rest
  sleuth:
    sampler:
      percentage: 1
  rabbitmq:
    port: 5672
    host: "${cloud.docker.host}"
    username: stayrascal
    password: stayrascal

flyway:
  enabled: true
  out-of-order: true
  encoding: UTF-8

cloud:
  jersey:
    Access-Control-Allow-Origin: '*'
    access_control_allow_origin: '*'
    swagger:
      version: '0.0.1'
      host: '${cloud.docker.host}:8078'
      scheme: 'http'
      base-path: /rest
  allowReloadTestData: true
  auth:
    admin_token_expire_minutes: 30
    allow_public_access: true
    randomKeyLength: 6
    email:
      defaultKeyExpireMinutes: 1440
      title:
      contentTemplate:

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 1000
      circuitBreaker:
        enabled: true
        requestvolumeThreshold: 1000
        sleepWindowInMilliseconds: 5000
        errorThresholdPercentage: 50

server:
  port: 8078
  context-path: /
  servlet-path: /
  tomcat:
    accesslog:
      enabled: true
      directory: /apps/boot/logs

logging:
  level:
    org.springframework.web: info
    com.stayrascal.cloud: info
    org.hibernate: ERROR
  config: classpath:logback-spring.xml

management:
  context-path: /system

eureka:
  instance:
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health

endpoints:
  env:
    enabled: true

---
spring:
  profiles: default
cloud:
  docker:
    host: localhost

---
spring:
  profiles: docker
cloud:
  docker:
    host: 192.168.99.100
