---
cluster.name: docker-cluster

network.host: 0.0.0.0

discovery.zen.minimum_master_nodes: 1

discovery.type: single-node

bootstrap.memory_lock: true

xpack:
  security.enabled: false
  monitoring.enabled: false
  ml.enabled: false
  graph.enabled: false
  watcher.enabled: false
