eureka:
  client:
    service-url:
      defaultZone: http://stayrascal:stayrascal@${cloud.docker.host}:8761/eureka/
#  instance:
#    hostname: infr-config-server

---
spring:
  profiles: default
cloud:
  docker:
    host: localhost

---
spring:
  profiles: docker
cloud:
  docker:
    host: 192.168.99.100
