spring:
  application:
    name: infra-config-server
#  rabbitmq:
#    port: 5672
#    host: localhost
#    username: springcloud
#    password: 123456
  cloud:
    inetutils:
      ignored-interfaces:
        - docker0
        - veth.*

server:
  port: 8888

eureka:
  instance:
    hostname: "${cloud.docker.host}" # infra-config-server
  client:
    service-url:
      defaultZone: http://stayrascal:stayrascal@${cloud.docker.host}:8761/eureka/

---
spring:
  profiles: default
cloud:
  docker:
    host: localhost

---
spring:
  profiles: docker
cloud:
  docker:
    host: 192.168.99.100
