spring:
  application:
    name: infra-config-server
  cloud:
    config:
      server:
        bootstrap: true
        git:
          uri: file://${user.home}/workspace/java/microservices/config-repo
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://192.168.99.100:8761/eureka/

