spring:
  application:
    name: service-order
  aop:
    auto: true
    proxy-target-class: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jersey:
    application-path: /rest
  sleuth:
    sampler:
      percentage: 1.0
  rabbitmq:
    port: 5672
    host: "${cloud.docker.host}"
    username: stayrascal
    password: stayrascal

flyway:
  enabled: true
  out-of-order: true
  encoding: UTF-8

cloud:
  jersey:
    access_control_allow_origin: '*'
    swagger:
      version: '0.0.1'
      host: 'localhost:8079'
      scheme: 'http'
      base-path: /rest
  auth:
    admin_token_expire_minutes: 30
    allow_public_access: true
  allowReloadTestData: true
  transaction:
    weChat:
      appId: wxcf0848f15d297fb3
      secret: da2605c98f732ba23475d9affc427f3f
      token: iN09j41p3mr5
      partnerKey: Br4AwHiDU3hHRGj6gGWFtPvkANFFHCqi
      encodingAesKey: CiXqCms3W9kcm7AR7hTTpHnawJ8nJl1zt9L2reTyviN
      mchId: 10014392
      notifyUrl: https://localhost:9441/rest/we-chat/notify

  weChat:
    redirectUrl: https://click-n-collect.exmertec.com/wechat-auth

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutMilliseconds: 1000
      cirsuitBreaker:
        enabled: true
        requestVolumeThreshold: 1000
        sleepWindowInMilliseconds: 5000
        errorThresholdPercentage: 50

server:
  port: 8079
  context-path: /
  servlet-path: /
  tomcat:
    accesslog:
      enabled: true
      directory: /apps/boot/logs

management:
  context-path: /system

eureka:
  instance:
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR
    me.chanjat.weixin.mp: DEBUG
  config: classpath:logback-spring.xml

feign:
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,appliaiton/json
      min-request-size: 2048
    response:
      enabled: true


  httpclient:
    enabled: true